[project]
name = "xlsx-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ics>=0.7.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "xlrd>=2.0.2",
]
